services:

    router:
        env_file:
          - path: .env.${ENV_STAGE:-dev}
            required: false
        environment:
              VIRTUAL_HOST: "${PROJECT_NAME}.${PROJECT_DOMAIN}"
              VIRTUAL_PORT: 80
        build:
            context: ./dockerfiles/infrastructure
            dockerfile: router.dockerfile
        image: ${PROJECT_NAME}/router
        container_name: ${PROJECT_NAME}-router
        volumes:
            - ./code:/var/www/html # static
            - ./config/nginx/conf.d:/etc/nginx/conf.d # config
            - ./config/nginx/vhost.d/${ENV_STAGE:-dev}:/etc/nginx/vhost.d # config
            - ./logs/nginx:/var/log/nginx # logs
        restart: unless-stopped
        networks:
            - inner
            - nginx-proxy

    backend:
        env_file:
          - path: .env.${ENV_STAGE:-dev}
            required: false
        build:
            context: ./dockerfiles/backend
            dockerfile: backend.dockerfile
            target: ${ENV_STAGE:-dev}
        profiles: ["backend"]
        image: ${PROJECT_NAME}/backend
        container_name: ${PROJECT_NAME}-backend
        environment:
            APP_UID: ${APP_UID}
            APP_GID: ${APP_GID}
            PHP_IDE_CONFIG: "serverName=${PROJECT_NAME}.${PROJECT_DOMAIN}"
            DATABASE_URL: "${DB_SCHEME}://${PROJECT_NAME}:${DB_PASSWORD}@storage:${DB_PORT_INTERNAL}/${PROJECT_NAME}?charset=${DB_CHARSET}"
        working_dir: /var/www/html/backend
        volumes:
            - ./config/php-ini/php.ini:/usr/local/etc/php/conf.d/zz-php.ini:ro #php-ini
            - backend_var:/var/www/html/var
            - backend_vendor:/var/www/html/vendor
            - backend_uploads:/var/www/html/public/uploads
        networks:
            - inner
        extra_hosts:
            host.docker.internal: host-gateway

    frontend:
      env_file:
        - path: .env.${ENV_STAGE:-dev}
          required: false
      build:
          context: ./dockerfiles/frontend
          dockerfile: frontend.dockerfile
      profiles: ["frontend"]
      image: ${PROJECT_NAME}/frontend
      container_name: ${PROJECT_NAME}-frontend
      working_dir: /var/www/html/frontend
      volumes:
          - frontend_node_modules:/var/www/html/node_modules
      environment:
          APP_UID: ${APP_UID}
          APP_GID: ${APP_GID}
          ENV_STAGE: ${ENV_STAGE:-dev}
          __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: ${PROJECT_NAME}.${PROJECT_DOMAIN}
      networks:
          - inner
      stdin_open: true
      tty: true

    # mariadb | postgres
    storage:
        env_file:
          - path: .env.${ENV_STAGE:-dev}
            required: false
        build:
            context: ./dockerfiles/storage
            dockerfile: ${DB_DOCKERFILE}
        profiles: ["storage"]
        image: ${PROJECT_NAME}/storage
        container_name: ${PROJECT_NAME}-storage
        volumes:
            - ${DB_DATA_VOLUME}
        environment:
            POSTGRES_DB: ${PROJECT_NAME}
            POSTGRES_USER: ${PROJECT_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
            MARIADB_DATABASE: ${PROJECT_NAME}
            MARIADB_USER: ${PROJECT_NAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
        command: ${DB_COMMAND}
        restart: unless-stopped
        networks:
            - inner

volumes:
  backend_var:
  backend_vendor:
  backend_uploads:
  frontend_node_modules:
  storage_data:

networks:
    nginx-proxy:
        external: true
        name: nginx-proxy
    inner:
        driver: bridge
