# Стадийное дополнение к docker-compose.yml для окружения prod.
# Портов наружу не публикует: доступ к сервисам — только через router и сеть inner.
services:
    router:
        environment:
            LETSENCRYPT_HOST: "${PROJECT_NAME}.${PROJECT_DOMAIN}"
            LETSENCRYPT_EMAIL: "${SSL_EMAIL}"
            HTTPS_METHOD: "redirect"
            HSTS: "max-age=31536000"

    backend:
        volumes:
            - ./code:/var/www/html:ro # code
            - ./config/php-ini/php-prod.ini:/usr/local/etc/php/conf.d/zzz-prod-override-php.ini:ro #php-ini override

    frontend:
        volumes:
          - ./code/frontend:/var/www/html:ro
