services:

    # nginx router
    router:
        env_file:
          - path: .env.${APP:-dev}
            required: false
        build:
            context: ./dockerfiles/infrastructure
            dockerfile: router.dockerfile
        image: ${PROJECT_NAME}/router
        container_name: ${PROJECT_NAME}-router
        volumes:
            - ./code:/var/www/html
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - ./config/nginx/vhost.d/${APP:-dev}:/etc/nginx/vhost.d
            - ./logs/nginx:/var/log/nginx
        restart: unless-stopped
        networks:
            - inner
            - nginx-proxy

    # php-fpm
    app:
        env_file:
          - path: .env.${APP:-dev}
            required: false
        build:
            context: ./dockerfiles/app
            dockerfile: app.dockerfile
            target: ${APP:-dev}
        image: ${PROJECT_NAME}/php
        container_name: ${PROJECT_NAME}-app
        environment:
            VIRTUAL_HOST: "${PROJECT_NAME}.${PROJECT_DOMAIN}"
            XDEBUG_CONFIG: "remote_host=host.docker.internal mode=debug remote_port=${XDEBUG_REMOTE_PORT}"
            PHP_IDE_CONFIG: "serverName=${PROJECT_NAME}"
        working_dir: /var/www/html/backend
        volumes:
            - ./code:/var/www/html # code
            - ./config/php-ini:/usr/local/etc/php # php.ini
            - ./logs/php:/log/php # logs
        networks:
            - inner
        extra_hosts:
            host.docker.internal: host-gateway

    # node
    node:
      env_file:
        - path: .env.${APP:-dev}
          required: false
      build:
          context: ./dockerfiles/node
          dockerfile: node.dockerfile
      image: ${PROJECT_NAME}/node
      container_name: ${PROJECT_NAME}-node
      working_dir: /var/www/html/frontend
      volumes:
          - ./code:/var/www/html
      ports:
          - "${NODE_EXTERNAL_PORT}:5173"
      networks:
          - inner
      stdin_open: true
      tty: true

    # mariadb | postgres
    db:
        env_file:
          - path: .env.${APP:-dev}
            required: false
        build:
            context: ./dockerfiles/db
            dockerfile: ${DB_DOCKERFILE}
        image: ${PROJECT_NAME}/db
        container_name: ${PROJECT_NAME}-db
        volumes:
            - ${DB_DATA_VOLUME}
        environment:
            POSTGRES_DB: ${PROJECT_NAME}
            POSTGRES_USER: ${PROJECT_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
            MARIADB_USER: ${PROJECT_NAME}
            MARIADB_PASSWORD: ${PROJECT_NAME}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:${DB_PORT_INTERNAL}"
        command: ${DB_COMMAND}
        restart: unless-stopped
        networks:
            - inner

networks:
    nginx-proxy:
        external: true
        name: nginx-proxy
    inner:
        driver: bridge