server {

    listen 80;
    listen 443;

    server_name billing.loc;
    access_log /var/log/nginx/access.log;

    # > Errors
    # 404
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    # < Errors

    # > Static
	# Resorces
	#location ~ \.(js|css|woff|woff2|ttf|svg|truetype)$ {
	#	root /var/www/html/frontend;
	#	try_files $uri =404;
	#}

	# Assets
	#location ~ \.(jpg|jpeg|png|ico|htm|html)$ {
	#	root /var/www/html/frontend;
	#	try_files $uri =404;
	#}
    # > Static

    # Backend
    location /api/ {
        set $upstream_keepalive false;
        include fastcgi_params;
        fastcgi_pass billing-app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html/backend/public/index.php;
    }

    # Frontend
    location / {
        root /var/www/html/frontend/dist;
        try_files $uri $uri/ /index.html;
    }
}
