# Backend
location / {

    access_log /var/log/nginx/access_backend.log;

    set $upstream_keepalive false;
    include fastcgi_params;
    fastcgi_pass {PROJECT_NAME}-backend:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME /var/www/html/backend/index.php;
}
